backend_address_pool_name      = "backend_address_pool_name"
frontend_port_name             = "frontend_port_name"
frontend_ip_configuration_name = "frontend_ip_configuration_name"
http_setting_name              = "http_setting_name"
listener_name                  = "listener_name"
request_routing_rule_name      = "request_routing_rule_name"
redirect_configuration_name    = "redirect_configuration_name"